### ISSUE TITLE
I cannot upload a file, giving the message: System.IO.IOException: The handle is invalid

### ISSUE THREAD

**Issue by psavva** [hartez/PneumaticTube#25]
Uploading Backup20180809.rar to /Backups
Ctrl-C to cancel
File is larger than 150MB, using chunked uploading.
An error occurred and your file was not uploaded.
System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at PneumaticTube.PercentProgressDisplay.Report(Int64 value)
   at PneumaticTube.DropboxClientExtensions.<UploadChunked>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PneumaticTube.Program.<Upload>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PneumaticTube.Program.<Upload>d__2.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at PneumaticTube.Program.Main(String[] args)
---> (Inner Exception #0) System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at PneumaticTube.PercentProgressDisplay.Report(Int64 value)
   at PneumaticTube.DropboxClientExtensions.<UploadChunked>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PneumaticTube.Program.<Upload>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PneumaticTube.Program.<Upload>d__2.MoveNext()<---

**Comment by psavva** [comment]
To Simulate, create a batch file:

backup.bat
with contents:

`
@echo off
> C:\Backup\%date:~-4,4%%date:~-10,2%%date:~7,2%.log (
cd "C:\PneumaticTube"
pneumatictube -f C:\Backup\Backup%date:~-4,4%%date:~-10,2%%date:~7,2%.rar -p /Backups
)
`

When running just the command from cmd, then it runs OK.
`pneumatictube -f C:\Backup\Backup%date:~-4,4%%date:~-10,2%%date:~7,2%.rar -p /Backups
`
