### ISSUE TITLE
Error running from command line

### ISSUE THREAD

**Issue by flamingtoast13** [hartez/PneumaticTube#8]
C:\Users\trainingstation\Downloads\PneumaticTube>pneumatictube.exe -f C:\Windows
\Temp\UP5LJZZILKP.log -p RemoteLogs
You'll need to authorize this account with PneumaticTube; a browser window will
now open asking you to log into dropbox and allow the app. When you've done that
, hit Enter.

Unhandled Exception: DropNet.Exceptions.DropboxException: Exception of type 'Dro
pNet.Exceptions.DropboxException' was thrown.
   at DropNet.DropNetClient.Execute(ApiType apiType, IRestRequest request)
   at DropNet.DropNetClient.GetToken()
   at PneumaticTube.Program.Main(String[] args)

On a sidenote, I'm trying to integrate this into powershell, but I keep getting this error. I only want to upload 1KB log files.

**Comment by hartez** [comment]
Did the browser window open to the Dropbox login page? Or does the error occur before the login page is opened?

**Comment by flamingtoast13** [comment]
The browser never opened ~

**Comment by hartez** [comment]
What OS are you using?

**Comment by hartez** [comment]
@flamingtoast13 Was this on Windows 8? It might be an issue with default browser configuration. I'm going to add a fallback to IE if the default browse can't be opened.

**Comment by flamingtoast13** [comment]
Its windows 7. Chome is the default browser though and I imagine that could be finicky?
